### ISSUE TITLE
Remove WEP support

### ISSUE THREAD

**Issue by gagarine** [RedoXyde/nabgcc#3]
WEP should never be used... it can be removed to make the firmware a bit smaller.

**Comment by RedoXyde** [comment]
Well... size is not (yet)° an issue and I'm not fond of removing stuff that works; it's already difficult enough to add working stuff  😆  
I really don't have time to work much on the firmware anyway, but I will keep that in mind in case size becomes important.

Meanwhile, if you think it is important, please fork, remove the WEP parts and submit a PR :)

**Comment by gagarine** [comment]
Ahah I fully understand. If I have 2 months spear time I will perhaps try to switch on my nabaztag ;).
